airflow:
  default_args:
    owner                 : airflow
    start_date            : datetime(2022, 10, 14)
    depends_on_past       : False
    email_on_failure      : False
    email_on_retry        : False
    retries               : 0
    retry_delay           : 0
    catchup_by_default    : False


  dag:
    job_name              : 'HOPKINS_COVID_DATA_INGESTION'
    description           : 'Dag for ingesting processed data from HOPKINS covid data set'
    schedule_interval     : '@once'

dataflow:
  data_folder            : ''

  # mention load type here. full or incremental
  load_type               : 'full'